---
title: "Lab02.Rmd"
output: html_document
---

# R Programming (base)
# Adapted from ISLR Chapter 3 Lab: Introduction to R

# Indexing Data using []

```{r}
A=matrix(1:16,4,4, byrow = FALSE)
A
A[2,3]
A[c(1,3),c(2,4)]
A[1:3,2:4]
A[1:2,]
A[,1:2]
A[1,]
A[-c(1,3),]
A[-c(1,3),-c(1,3,4)]
dim(A)
```


# Loading Data

```{r}
#=read.table("https://raw.githubusercontent.com/monaejam/knowledge-Mining-Blog/gh-pages/data/Auto.data")
#fix(Auto)
Auto=read.table("https://raw.githubusercontent.com/monaejam/knowledge-Mining-Blog/gh-pages/data/Auto.data",header=T,na.strings="?")
#fix(Auto)
Auto=read.csv("https://raw.githubusercontent.com/monaejam/knowledge-Mining-Blog/gh-pages/data/Auto.csv",header=T,na.strings="?")
#fix(Auto)
dim(Auto)
Auto[1:4,]
Auto=na.omit(Auto)
dim(Auto)
names(Auto)


# Additional Graphical and Numerical Summaries

plot(Auto$cylinders, Auto$mpg)
plot(Auto$cylinders, Auto$mpg)
attach(Auto)
plot(Auto$cylinders, Auto$mpg)
cylinders=as.factor(Auto$cylinders)
plot(Auto$cylinders, Auto$mpg)
plot(Auto$cylinders, Auto$mpg, col="red")
#plot(Auto$cylinders, Auto$mpg, col="red", varwidth=T)
#plot(Auto$cylinders, Auto$mpg, col="red", varwidth=T,horizontal=T)
#plot(Auto$cylinders, Auto$mpg, col="red", varwidth=T, xlab="cylinders", ylab="MPG")
hist(Auto$mpg)
hist(Auto$mpg,col=2)
hist(Auto$mpg,col=2,breaks=15)
#pairs(Auto)
#pairs(~ mpg + displacement + horsepower + weight + acceleration, Auto)
plot(Auto$horsepower,Auto$mpg)
identify(Auto$horsepower,Auto$mpg,Auto$name)
summary(Auto)
summary(mpg)
```

# Linear Regression
# install.packages("MASS")
```{r}
library(MASS)
library(ISLR)
```


# Simple Linear Regression

```{r}
#fix(Boston)
names(Boston)
lm.fit=lm(Boston$medv~Boston$lstat)
attach(Boston)
lm.fit=lm(medv~lstat,data=Boston)
attach(Boston)
lm.fit=lm(medv~lstat)
lm.fit
summary(lm.fit)
names(lm.fit)
coef(lm.fit)
confint(lm.fit)
predict(lm.fit,data.frame(lstat=(c(5,10,15))), interval="confidence")
predict(lm.fit,data.frame(lstat=(c(5,10,15))), interval="prediction")
plot(lstat,medv)
abline(lm.fit)
abline(lm.fit,lwd=3)
abline(lm.fit,lwd=3,col="red")
plot(lstat,medv,col="red")
plot(lstat,medv,pch=16)
plot(lstat,medv,pch="+")
plot(1:20,1:20,pch=1:20)
par(mfrow=c(2,2))
plot(lm.fit)
plot(predict(lm.fit), residuals(lm.fit))
plot(predict(lm.fit), rstudent(lm.fit))
plot(hatvalues(lm.fit))
which.max(hatvalues(lm.fit))
```


# Multiple Linear Regression

```{r}
lm.fit=lm(medv~lstat+age,data=Boston)
summary(lm.fit)
lm.fit=lm(medv~.,data=Boston)
summary(lm.fit)
library(car)
vif(lm.fit)
lm.fit1=lm(medv~.-age,data=Boston)
summary(lm.fit1)
lm.fit1=update(lm.fit, ~.-age)

```

# Interaction Terms

```{r}
summary(lm(medv~lstat*age,data=Boston))

```

# Non-linear Transformations of the Predictors

```{r}
lm.fit2=lm(medv~lstat+I(lstat^2))
summary(lm.fit2)
lm.fit=lm(medv~lstat)
anova(lm.fit,lm.fit2)
par(mfrow=c(2,2))
plot(lm.fit2)
lm.fit5=lm(medv~poly(lstat,5))
summary(lm.fit5)
summary(lm(medv~log(rm),data=Boston))
```


# Qualitative Predictors

```{r}
#fix(Carseats)
names(Carseats)
lm.fit=lm(Sales~.+Income:Advertising+Price:Age,data=Carseats)
summary(lm.fit)
attach(Carseats)
contrasts(ShelveLoc)
```


# Writing Functions

```{r}
#LoadLibraries
#LoadLibraries()
LoadLibraries=function(){
  library(ISLR)
  library(MASS)
  print("The libraries have been loaded.")
}
LoadLibraries
LoadLibraries()
```

